### ISSUE TITLE
Need routes for trafic returning to VPN users

### ISSUE THREAD

**Issue by felddy** [cisagov/cool-sharedservices-networking#11]
I don't think traffic is being routed back to the VPN clients.  We need routes sending all `10.128.248.0/21` to the OpenVPN server.

**Comment by jsf9k** [comment]
@felddy - I have no idea what you were seeing.  I assume you were talking to a FreeIPA server or replica, since those are the only instances deployed to the COOL right now other than the OpenVPN server.  The FreeIPA server and replicas are set up to only accept connections from the FreeIPA client and server security groups or certain privileged IPs.  Previously, only the OpenVPN server was in the client security group, only the replicas were in the server security group, and only the devs' home IPs were in the list of privileged IPs.  I suspect this is why you were not seeing traffic.

Security groups cannot be shared across VPCs, so I have added the entire COOL `/9` CIDR to the list of privileged IPs.  (I also removed our home IPs since the FreeIPA server and replicas are now in private subnets.)  You can see this change at jsf9k/cool-tfvars@6a0de6f.

This change has been deployed, so please let me know if it resolves your issue.

**Comment by felddy** [comment]
Sorry I didn't go into more detail.  This was just a reminder for Monday.  VPN clients are unable to get DNS responses.  My theory is that the DNS service at `10.128.0.2` is unable to route responses back to the clients in the `10.128.248.0/21` subnet.  So a route needs to be created sending that traffic to the VPN server for routing.   Theory...

**Comment by jsf9k** [comment]
@felddy, please see cisagov/cool-sharedservices-networking#12 and cisagov/cool-sharedservices-openvpn@f7ffb60c4b02f3cdb3b2ac77ad6c2c352e602e10.  I haven't deployed those changes yet because I can't do it without redeploying the OpenVPN server.  (This is for nonsense reasons - our `isort` pre-commit hook added some comments to the cloud-init python code.)

Let's work together tomorrow to deploy these changes and see if it fixes your issue.

**Comment by jsf9k** [comment]
Well this is a fine kettle of fish:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_route.private_vpn_routes["10.128.0.0/24"] will be created
  + resource "aws_route" "private_vpn_routes" {
      + destination_cidr_block     = "10.128.248.0/21"
      + destination_prefix_list_id = (known after apply)
      + egress_only_gateway_id     = (known after apply)
      + gateway_id                 = (known after apply)
      + id                         = (known after apply)
      + instance_id                = "i-03d0d14056dafd1e7"
      + instance_owner_id          = (known after apply)
      + nat_gateway_id             = (known after apply)
      + network_interface_id       = (known after apply)
      + origin                     = (known after apply)
      + route_table_id             = "rtb-022632c9ceaa6c55e"
      + state                      = (known after apply)
    }

  # aws_route.private_vpn_routes["10.128.1.0/24"] will be created
  + resource "aws_route" "private_vpn_routes" {
      + destination_cidr_block     = "10.128.248.0/21"
      + destination_prefix_list_id = (known after apply)
      + egress_only_gateway_id     = (known after apply)
      + gateway_id                 = (known after apply)
      + id                         = (known after apply)
      + instance_id                = "i-03d0d14056dafd1e7"
      + instance_owner_id          = (known after apply)
      + nat_gateway_id             = (known after apply)
      + network_interface_id       = (known after apply)
      + origin                     = (known after apply)
      + route_table_id             = "rtb-0b451f1b5f6f43148"
      + state                      = (known after apply)
    }

  # aws_route.private_vpn_routes["10.128.2.0/24"] will be created
  + resource "aws_route" "private_vpn_routes" {
      + destination_cidr_block     = "10.128.248.0/21"
      + destination_prefix_list_id = (known after apply)
      + egress_only_gateway_id     = (known after apply)
      + gateway_id                 = (known after apply)
      + id                         = (known after apply)
      + instance_id                = "i-03d0d14056dafd1e7"
      + instance_owner_id          = (known after apply)
      + nat_gateway_id             = (known after apply)
      + network_interface_id       = (known after apply)
      + origin                     = (known after apply)
      + route_table_id             = "rtb-08ff45c22c66f3bb6"
      + state                      = (known after apply)
    }

  # aws_route.public_vpn_route will be created
  + resource "aws_route" "public_vpn_route" {
      + destination_cidr_block     = "10.128.248.0/21"
      + destination_prefix_list_id = (known after apply)
      + egress_only_gateway_id     = (known after apply)
      + gateway_id                 = (known after apply)
      + id                         = (known after apply)
      + instance_id                = "i-03d0d14056dafd1e7"
      + instance_owner_id          = (known after apply)
      + nat_gateway_id             = (known after apply)
      + network_interface_id       = (known after apply)
      + origin                     = (known after apply)
      + route_table_id             = "rtb-0fce54fa21948ed97"
      + state                      = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "production"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_route.public_vpn_route: Creating...
aws_route.private_vpn_routes["10.128.2.0/24"]: Creating...
aws_route.private_vpn_routes["10.128.0.0/24"]: Creating...
aws_route.private_vpn_routes["10.128.1.0/24"]: Creating...

Error: Error creating route: InvalidParameterValue: This route table is used by a subnet, and doesn't support route destination which are more specific than VPC local CIDR.
        status code: 400, request id: 01e8b982-22d2-428d-8a82-d9848ffceb17

  on vpc_routes.tf line 7, in resource "aws_route" "public_vpn_route":
   7: resource "aws_route" "public_vpn_route" {



Error: Error creating route: InvalidParameterValue: This route table is used by a subnet, and doesn't support route destination which are more specific than VPC local CIDR.
        status code: 400, request id: ebfe18e2-e31b-41a2-955d-a7fd9d153e80

  on vpc_routes.tf line 14, in resource "aws_route" "private_vpn_routes":
  14: resource "aws_route" "private_vpn_routes" {



Error: Error creating route: InvalidParameterValue: This route table is used by a subnet, and doesn't support route destination which are more specific than VPC local CIDR.
        status code: 400, request id: 5bef45ec-e0b6-47b1-b3c8-0be8a1c1d677

  on vpc_routes.tf line 14, in resource "aws_route" "private_vpn_routes":
  14: resource "aws_route" "private_vpn_routes" {



Error: Error creating route: InvalidParameterValue: This route table is used by a subnet, and doesn't support route destination which are more specific than VPC local CIDR.
        status code: 400, request id: dbe8da81-5287-4fa9-a062-275602f20e34

  on vpc_routes.tf line 14, in resource "aws_route" "private_vpn_routes":
  14: resource "aws_route" "private_vpn_routes" {
```

**Comment by jsf9k** [comment]
Closed the issue by mistake.  Sorry about that.

**Comment by jsf9k** [comment]
I'm unsure how to route this traffic.  [Here](https://www.terraform.io/docs/providers/aws/r/route.html) is the documentation for the Terraform `aws_route` resource, although as you can see from the errors above I'm not allowed to specify anything more specific than a VPC local CIDR for VPC subnet routing tables.  Offhand, I can think of two things that might help:
* Put the OpenVPN server in its own subnet with a CIDR identical to that of the client network.
* Turn on NAT for the OpenVPN server.

[These instructions](https://aws.amazon.com/blogs/awsmarketplace/setting-up-openvpn-access-server-in-amazon-vpc/) indicate that NAT is not necessary, but they do not go into specifics.

**Comment by felddy** [comment]
I read those same docs.  Lets try the routing/subnet method first.  If that doesn't work we can fail back to the NAT. 

Now might also be a good time to consider how this will scale with regards to load-balancing users across multiple VPN servers.  The NATing might make more sense in that case.

**Comment by jsf9k** [comment]
There is always [this managed solution](https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/what-is.html) too, if we can get the certificate foo to work properly.

**Comment by jsf9k** [comment]
The routing method did not work, since there is no way to attach a routing table to a Transit Gateway attachment.  (One can attach route tables to Internet Gateways and Virtual Private Gateways, but not TGW attachments.)

We have decided to instead use NAT on the OpenVPN instance.  This ensures all traffic for the clients is routed through the OpenVPN instance.

**Comment by jsf9k** [comment]
@felddy, do you agree with me that we can close this issue?  AWS Mike was pretty clear that we have to go with NAT in this case.

**Comment by felddy** [comment]
Yes.  NAT has solved this issue.  I'll open an issue to make the NAT changes to the OpenVPN server.
